### ISSUE TITLE
Getting error when trying to deploy Lex bot without clarification prompts

### ISSUE THREAD

**Issue by agnel0410** [aws-samples/amazon-lex-bot-deploy#9]
* amazon-lex-bot-deploy version:
* Python version: 3.7.5
* Operating System: Mac

### Description

Getting error when trying to deploy Lex bot without clarification prompts.

Error:
INFO:amazon_lex_bot_deploy.amazon_lex_bot_deploy:deployed all intents
ERROR:__main__:'clarificationPrompt'
Traceback (most recent call last):
  File "./build-lexbots.py", line 131, in <module>
    check=True)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['lex-bot-deploy', '-s', './build/lexbots/SLU_MainMenu_Export.json']' returned non-zero exit status 1.
ERROR: could not deploy ./build/lexbots/SLU_MainMenu_Export.json

### What I Did

```

        try:
            response = subprocess.run([
                "lex-bot-deploy",
                "-s",
                path_to_json],
                check=True)

            print(response)
        except:
            traceback.print_exc(file=sys.stdout)
            print("ERROR: could not deploy {0}".format(path_to_json))
            exit(99)

If there was a crash, please include the traceback here.
```

**Comment by agnel0410** [comment]
Upgraded to the latest lex-bot-deploy and that fixed the issue.Thanks
